# Generated by Django 5.2 on 2025-09-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('fecha_creacion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='CarritoDetalle',
            fields=[
                ('idcarritodetalle', models.AutoField(db_column='idCarritoDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'carritodetalle',
            },
        ),
    ]
