# Generated by Django 5.2 on 2025-09-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('fecha_creacion', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='CarritoDetalle',
            fields=[
                ('idcarritodetalle', models.AutoField(db_column='idCarritoDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='carrito.carrito')),
                ('producto', models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'db_table': 'carritodetalle',
            },
        ),
    ]
