# Generated by Django 5.2 on 2025-10-29 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='carritodetalle',
            name='carrito',
            field=models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='carrito.carrito'),
        ),
        migrations.AddField(
            model_name='carritodetalle',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
