# Generated by Django 5.2 on 2025-10-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=14)),
                ('fecha_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.CharField(max_length=45)),
                ('total', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=9)),
                ('direccion_envio', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('idpedidodetalle', models.AutoField(db_column='idPedidoDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pedidodetalle',
            },
        ),
    ]
