# Generated by Django 5.2 on 2025-09-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.CharField(max_length=45)),
                ('total', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=9)),
                ('direccion_envio', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=14)),
                ('fecha_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
                ('pedido', models.ForeignKey(db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('idpedidodetalle', models.AutoField(db_column='idPedidoDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('producto', models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'db_table': 'pedidodetalle',
            },
        ),
    ]
