# Generated by Django 5.2 on 2025-10-29 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
