# Generated by Django 5.2 on 2025-09-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('iddispositivo', models.AutoField(db_column='idDispositivo', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=8, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivo',
            },
        ),
    ]
