# Generated by Django 5.2.7 on 2025-11-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(blank=True, choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('OPPO', 'OPPO'), ('Vivo', 'Vivo'), ('Huawei', 'Huawei'), ('Realme', 'Realme'), ('Honor', 'Honor'), ('OnePlus', 'OnePlus'), ('Motorola', 'Motorola'), ('Sony', 'Sony'), ('Nokia', 'Nokia'), ('Infinix', 'Infinix'), ('Tecno', 'Tecno'), ('Google', 'Google')], max_length=20, null=True),
        ),
    ]
