# Generated by Django 5.2.7 on 2025-11-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0003_alter_dispositivo_marca'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('tipo_servicio', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Solicitud'), ('en proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('olvidado', 'Olvidado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asesor', models.ForeignKey(db_column='id_asesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_asesor', to='usuarios.usuarios')),
                ('cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_cliente', to='usuarios.usuarios')),
                ('dispositivo', models.ForeignKey(db_column='id_dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='dispositivos.dispositivo')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='HistorialCita',
            fields=[
                ('idhistorial', models.AutoField(db_column='idHistorial', primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(choices=[('Solicitud', 'Solicitud'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Olvidado', 'Olvidado')], db_column='estado_anterior', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('Solicitud', 'Solicitud'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Olvidado', 'Olvidado')], db_column='estado_nuevo', max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='fecha_cambio')),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('cita', models.ForeignKey(db_column='idCita', on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='citas.cita')),
            ],
            options={
                'db_table': 'historial_cita',
                'managed': True,
            },
        ),
    ]
