# Generated by Django 5.2 on 2025-10-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCita',
            fields=[
                ('idhistorial', models.AutoField(db_column='idHistorial', primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(choices=[('Solicitud', 'Solicitud'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Olvidado', 'Olvidado')], db_column='estado_anterior', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('Solicitud', 'Solicitud'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Olvidado', 'Olvidado')], db_column='estado_nuevo', max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='fecha_cambio')),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
            ],
            options={
                'db_table': 'historial_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('fecha_cita', models.CharField(max_length=50)),
                ('hora_cita', models.CharField(max_length=45)),
                ('tipo_servicio', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Solicitud'), ('en proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('olvidado', 'Olvidado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
    ]
