# Generated by Django 5.2 on 2025-09-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('fecha_cita', models.CharField(max_length=50)),
                ('hora_cita', models.CharField(max_length=45)),
                ('tipo_servicio', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asesor', models.ForeignKey(db_column='id_asesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_asesor', to='usuarios.usuarios')),
                ('cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_cliente', to='usuarios.usuarios')),
                ('dispositivo', models.ForeignKey(db_column='id_dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='dispositivos.dispositivo')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
    ]
