# Generated by Django 5.2 on 2025-10-29 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('dispositivos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='asesor',
            field=models.ForeignKey(db_column='id_asesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_asesor', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_cliente', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='cita',
            name='dispositivo',
            field=models.ForeignKey(db_column='id_dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='dispositivos.dispositivo'),
        ),
    ]
