# Generated by Django 5.2 on 2025-10-29 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_fecha_cita_alter_cita_hora_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
