# Generated by Django 5.2 on 2025-10-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_hora_cita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialcita',
            options={'managed': True},
        ),
    ]
