# Generated by Django 5.2 on 2025-10-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_historialcita_options'),
    ]

    operations = [
       migrations.AddField(
            model_name='historialcita',
            name='cita',
            field=models.ForeignKey(db_column='idCita', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='citas.cita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.CharField(max_length=10),
        ),
    ]
