# Generated by Django 5.2 on 2025-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_historialcita_cita_alter_cita_fecha_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(),
        ),
    ]
